name: MinePanel
version: 1.4.0
main: me.flaxi.serverwebadmin.ServerWebAdmin
author: Flaxi
description: ServerWebAdmin is a lightweight Minecraft Spigot/Paper plugin that provides a web-based control panel
commands:
  webadmin:
    description: Server Web Admin command
    usage: /webadmin
    permission: serverwebadmin.use
permissions:
  serverwebadmin.use:
    description: Allow use ServerWebAdmin command
    default: op